# Generated by Django 3.1.5 on 2021-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicritere', '0002_auto_20210121_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Homme'), ('FEMALE', 'Femme')], default=1, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Coordinateur', 'Coordinateur'), ('Decideur', 'Decideur')], max_length=20, null=True),
        ),
    ]
