# Generated by Django 3.1.5 on 2021-02-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multicritere', '0003_auto_20210121_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Coordinateur', 'Coordinateur'), ('Decideur', 'Decideur'), ('Negociateur', 'Negociateur')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp', models.FileField(upload_to='')),
                ('weights', models.FileField(upload_to='')),
                ('decideur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multicritere.profile')),
            ],
        ),
    ]
