# Generated by Django 3.1.5 on 2021-02-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicritere', '0005_auto_20210227_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadecideur',
            name='mp',
            field=models.FileField(default='settings.MEDIA_ROOT/MPS/default.csv', upload_to='MPS'),
        ),
        migrations.AlterField(
            model_name='datacordinateur',
            name='mp',
            field=models.FileField(default='settings.MEDIA_ROOT/MPS/default.csv', upload_to='MPS'),
        ),
        migrations.AlterField(
            model_name='datadecideur',
            name='weights',
            field=models.FileField(default='settings.MEDIA_ROOT/Weights/default.csv', upload_to='Weights'),
        ),
    ]
